---

- hosts: all
#  connection: local
  gather_facts: true
  become: yes

  vars:
    in_vm: true
    cis_level_1_exclusions:
      - 1.1.14
      - 3.3.2
      - 3.3.3
      - 3.5.1.1
      - 3.5.1.2
      - 3.5.1.3
      - 3.5.1.4
      - 3.5.2.1
      - 3.5.2.2
      - 3.5.2.3
      - 3.5.2.4
    cis_level_2_exclusions:
      - 1.1.6
      - 1.1.7
      - 1.1.11
      - 1.1.12
      - 1.1.13
      - 4.1.1.3 # temporary until /var/log/audit files are transferred to another storage so they can be rotated/emptied from the disk


  roles:
    - ansible-cis-amazon-linux-2-master