# Standards: 0.11
---

- include: preflight.yml
  when: cis_apply_level_1_profile or cis_apply_level_2_profile

- include: partitioning.yml
  when: with_partitioning

# In container, we're root already. We don't want to install sudo if we can help it
#- include: "level-1.yml"
#  become: no
#  when: cis_apply_level_1_profile and in_container is defined
#
#- include: "level-2.yml"
#  become: no
#  when: cis_apply_level_2_profile and in_container is defined

- include: "level-1.yml"
  become: yes
  when: cis_apply_level_1_profile and in_vm is defined

- include: "level-2.yml"
  become: yes
  when: cis_apply_level_2_profile and in_vm is defined

- include: "policykit.yml"
  become: yes

#- name: Autorelabel (for SELinux) and reboot
#  become: yes
#  command: "touch /.autorelabel; reboot"

- name: flush handlers
  meta: flush_handlers
