# Standards: 0.11
---

# 1.1.10 Ensure noexec option set on /var/tmp partition

- name: 1.1.10 - Ensure noexec option set on /var/tmp partition - prereq 1
  shell: "lsblk -no UUID {{ cis_partition_dev_val_tmp }}"
  register: lsblk_vartmp_output

- name: 1.1.10 - Ensure noexec option set on /var/tmp partition
  mount:
    name: "{{ item.mountpoint }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    src: "UUID={{ lsblk_vartmp_output.stdout }}"
    opts: "{{ item.opts.split(',') | union(['noexec']) | join(',') }}"
  when: item.mountpoint == '/var/tmp'
  with_items: "{{ fs_mounts }}"
  tags:
    - level-1
    - section-1
    - "1.1.10"
    - scored
